# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

warnings_are_errors: false
sudo: false
cache: packages

matrix:
  include:
  - r: devel
    env: TRAVIS_R_VERSION_STRING=3.6.0
  - r: release
  - r: release
    pandoc: false
    env: PANDOC='none'
  - r: release
    os: osx
    pandoc: false
    env: PANDOC='mac-cran'
    latex: false
  - r: 3.6

